import type { GostProfile } from "../core/model";
import {
  pageA4,
  pageMargins,
  pageNumbers,
  fontFamilyRule,
  fontSizeRule,
  lineSpacingRule,
  indentRule,
  alignmentRule,
  colorRule,
  headingCaseRule,
  headingTrailingDotRule,
  headingUnderlineRule,
  headingHyphensRule,
  headingNumberingRule,
  headingSpacingRule,
  sectionNewPageRule,
  tocPresentRule,
  tableCaptionRule,
  figureCaptionRule,
  referencesPresentRule,
  referencesNumberingRule,
  referencesPatternRule,
} from "../rules";

/** Профиль проверки по ГОСТ 2.105-95 (ЕСКД. Общие требования к текстовым документам). */
export const gost210595: GostProfile = {
  id: "gost-2.105-95",
  name: "ГОСТ 2.105-95",
  description:
    "ЕСКД. Общие требования к текстовым документам. Страница, шрифты, абзацы, заголовки, таблицы, рисунки, список литературы.",
  rules: [
    pageA4,
    pageMargins,
    pageNumbers,
    fontFamilyRule,
    fontSizeRule,
    lineSpacingRule,
    indentRule,
    alignmentRule,
    colorRule,
    headingCaseRule,
    headingTrailingDotRule,
    headingUnderlineRule,
    headingHyphensRule,
    headingNumberingRule,
    headingSpacingRule,
    sectionNewPageRule,
    tocPresentRule,
    tableCaptionRule,
    figureCaptionRule,
    referencesPresentRule,
    referencesNumberingRule,
    referencesPatternRule,
  ],
};
